'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Contact
    
    '''<summary>
    '''AddStudent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddStudent As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ID_lb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ID_lb As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Username_lb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Username_lb As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''First_lb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents First_lb As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Middle_lb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Middle_lb As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Last_lb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Last_lb As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Address_lb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Address_lb As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Phone_lb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Phone_lb As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Country_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Country_tb As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''City_tb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents City_tb As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''State_lb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents State_lb As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ZIP_lb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ZIP_lb As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''BD_lb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BD_lb As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Major_lb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Major_lb As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''AddStudent_bttn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddStudent_bttn As Global.System.Web.UI.WebControls.Button
End Class
